export PATH="$HOME/bin:$HOME/go/bin:/opt/homebrew/bin:$PATH"
export EDITOR=hx

# Custom functions
# ===
# Ensure that the files we want to source actually exist.

function safe_source {
  test -e "$1" && source "$1"
}

# Shell integrations and includes
# ===

# Engage FZF
safe_source "$HOME/.fzf.zsh"

# use a fancy prompt
if command -v "starship" >/dev/null; then
  eval "$(starship init zsh)"
fi

# bun
[ -s "/Users/ivan.ostric/.bun/_bun" ] && source "/Users/ivan.ostric/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# br
safe_source "$HOME/.config/broot/launcher/bash/br"

# Environment variables
# ===

# Enable history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.zsh_history

# Default configuration for `fzf`
export FZF_DEFAULT_OPTS="\
  --ansi \
"
export FZF_DEFAULT_COMMAND="rg --hidden -g '!.git/' -l ."

# Default configuration for `bat`
export BAT_THEME="OneHalfDark"

# `cd` to any project from anywhere
export CDPATH=".:$HOME/Code"

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# This is what happens when you mix Go and Rust...
export CARGO_NET_GIT_FETCH_WITH_CLI=true
